mehta-lab/waveorder

requirements/default.txt
waveorder/visual.py

This PR adds faster functions for multi-dimensional data viewers through ipywidgets. The newly added functions are 
`image_stack_viewer_fast`, `rgb_stack_viewer_fast`, `parallel_4D_viewer_fast`, `parallel_5D_viewer_fast`, which are faster version of `image_stack_viewer`, `rgb_stack_viewer`, `parallel_4D_viewer`, `parallel_5D_viewer`, in `visual.py`.

Faster vis

---

.github/workflows/pytests.yml
.github/workflows/python-app.yml
.gitignore
examples/Reader_Writer_Examples/Writer_Example.ipynb
requirements/default.txt
requirements/test.txt
tests/conftest.py
tests/reader/test_multipagetiff.py
tests/reader/test_reader.py
tests/reader/test_singlepagetiff.py
tests/writer/test_physical_writer.py
tests/writer/test_stokes_writer.py
waveorder/io/__init__.py
waveorder/io/multipagetiff.py
waveorder/io/reader.py
waveorder/io/singlepagetiff.py
waveorder/io/writer.py

following github instructions on initializing for continuous integration
[](https://docs.github.com/en/actions/guides/setting-up-continuous-integration-using-workflow-templates)
Edit:
This creates a workflow file: `.github/workflows/pytests.yml`. This is a template provided by github and modified for our use.  What it accomplishes is primarily:
1. upon any push, run flake8 linter and pytest on ubuntu

init github actions

---

waveorder/util.py

add padding to wavelet denoising to account for the function only working with even dimensions.  Implements a fix for any nD array passed to the input

add padding

---

waveorder/waveorder_reconstructor.py

This is a short PR meant to improve the uPTI calibration scheme. This version estimates the angular offset of the linear polarizer used for calibration, while the past version finds the peak intensity of I0 channel for this estimation. The past version is not accurate when the sampling of the calibration curve is low.

Update the calibration scheme

---

tests/reader/test_reader.py
waveorder/io/reader.py

fix bug in z_step_size setter

---

waveorder/io/zarrfile.py

fix bug in MM meta

---

waveorder/io/zarrfile.py

catch specific error of MM data not present

add specific catch

---

waveorder/io/upti.py
waveorder/optics.py
waveorder/util.py

This PR mostly focuses on wrapping up the sub-FOV stitching functions in all the uPTI processing notebooks.

wrap up stitching-relavant functions and some compute functions for uPTI pipelines

---

examples/multiProcessing/QLIPP_4_states_fluor_deconv_waveorder.py

This script adds multiprocessing for QLIPP 4 states along with fluorescence deconvolution. Multiprocessing by @talonchandler, QLIPP code from notebook by @lihaoyeh

multiprocess for QLIPP & deconvolution

---

waveorder/io/multipagetiff.py

This PR is parallel to [this recOrder PR](https://github.com/mehta-lab/recOrder/pull/123), which [addresses this issue](https://github.com/mehta-lab/recOrder/issues/121). I will merge both PRs at the same time.

Fix ome-tif to zarr converter for acquisitions with micromanager beta

---

tests/conftest.py

Matches [`recOrder` PR 159](https://github.com/mehta-lab/recOrder/pull/159).

Don't delete test data

---

.github/workflows/pytests.yml
setup.cfg

Drop 3.7 and add 3.8, 3.9, 3.10

---

README.md

I just gave a final pass over the README to prepare for the `waveorder==1.0.0` release.

Fix link to example

---

waveorder/models/inplane_anisotropic_thin_pol3d.py
waveorder/models/phase_thick_3d.py
waveorder/optics.py

Minor renaming for consistency

`illumination_wavelength` -> `wavelength_illumination`

---

waveorder/util.py

Specify meshgrid indexing order

---

README.md

Tidying up the README for 2.0.0 release. 
Accidentally branched from `document-m1` #156, so we should merge that first.

Prepare README for 2.0.0

---

CITATION.cff

- update author order on @mattersoflight's suggestion
- adding @ziw-liu
- Change from "CZ Biohub" to "Chan Zuckerberg Biohub San Francisco" to match iohub
- update version and release date

Authorship and release updates

---

.github/workflows/pr.yml
.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
docs/QLIPP.md
docs/development-guide.md
docs/microscope-installation-guide.md
docs/software-installation-guide.md
pyproject.toml
tests/cli_tests/test_cli.py
tests/cli_tests/test_compute_tf.py
tests/cli_tests/test_reconstruct.py
tests/cli_tests/test_settings.py
tests/conftest.py
tox.ini
waveorder/acq/acq_functions.py
waveorder/calib/Calibration.py
waveorder/cli/utils.py
waveorder/plugin/tab_recon.py

Partial fix for #197 (not including pycro-manager).

Bump iohub and pydantic

---

.github/workflows/test.yml

adding a trigger to run tests on Pull requests
currently, tests only run on `push` ... which will work for all pushes to, say, branches... but *won't* run on a PR from a fork

run tests on pr

---

waveorder/plugin/tab_recon.py

Fixes loading default phase.yml and fluorescence.yml config files in GUI
