mehta-lab/waveorder

waveorder/io/multipagetiff.py
waveorder/io/reader.py
waveorder/io/singlepagetiff.py

**condition**
ome-tiff images acquired in 1.4.22 do not have "stageposition" key in their metadata
**solution**
changed the metadata assignment for 1.4.22 to exclude "stageposition" search
Additionally ...
I made a small refactor to match singlepage-multipage tiff class structures (created a `_set_mm_meta` method for singlepage-tiff reader.)

fixed 1.4.22 metadata search that errors on "stageposition"

---

waveorder/io/writer.py

Super small fix to change the default contrast limits from (0,180) to (0,pi) due to waveOrder spitting out orientation in radians

fix contrast limit bug in orientation

---

.github/workflows/pytests.yml
requirements/default.txt
requirements/test.txt
tests/reader/test_reader.py
waveorder/io/reader.py

Addresses issue #16 
This PR simply enables the raw ability to modify the multipage/singlepage tiff class's dimensions from the reader.
Might enable us to manually adjust image dimensions for acquisitions that have been cut short.  That condition requires additional testing.

Manual attribute assignment

---

waveorder/io/writer.py

In one condition of the writer, the t and c channel were flipped.  fixed this bug

fix incorrect assignment of channel, time, in one instance of the writer

---

waveorder/visual.py
waveorder/waveorder_reconstructor.py

This PR includes the following update:
1. improve the speed of uPTI deconvolution in `scattering_potential_tensor_recon_3D_vec` by 2x with `cupy`'s implementation on determinant computation (cupy v9 has a better algorithm than v4).
2. improve the speed of optic sign estimation in `scattering_potential_tensor_to_3D_orientation` by 5x with all gpu implementation (it will consume around 20% more gpu memory, we have option to use the original implementation)
3. fix bugs in the interactive visualization functions in `visual.py` (newer version of jupyter notebook requires plt.show() to properly plot in the ipywidget windows)

update uPTI solver

---

waveorder/optics.py
waveorder/util.py

This PR implements a function to compute the 3D orientation continuity map to suppress noisy retardance measurements in uPTI.

Added a function to compute 3D orientation continuity map

---

examples/multiProcessing/Phase3D_fluor_deconv_waveorder_all_channels.py

changed the default behavior of the phase & deconvolution multiprocessing [script](https://github.com/mehta-lab/waveorder/blob/waveorder_scripts/examples/multiProcessing/Phase3D_fluor_deconv_waveorder_all_channels.py) to run the full job and refactored it (more comments, all variables that must be set by user on top).

multiprocess script refactoring, set default to run full job

---

setup.cfg
waveorder/visual.py

This PR replaces the OpenCV image encoder with pillow. The 'jpg' name and docstring has been editted to match the actual codec (PNG). Related: #107, #97.

Replace OpenCV with pillow

---

tests/test_stokes.py
waveorder/stokes.py

This PR adds a completely rewritten version of all Stokes- and Mueller-related calculations in `waveorder`.
This rewrite was motived by the following questions:
- Q: how should we handle background correction of S3 to prepare it for deconvolution? A: keep track of S3 and use Mueller matrices to correct backgrounds. 
- how should we handle normalization (see the closed #103 for an earlier discussion)? A: no need to normalize in a separate step. 
- can we handle larger background retardances? A: yes, by estimating Mueller matrices. 
**Highlight improvements:**
- removal of normalization steps...instead of a two step reconstruction with a normalization followed by reconstruction, this implementation goes straight from Stokes parameters to (retardance, orientation, transmittance, …

New Stokes and Mueller module

---

waveorder/models/inplane_anisotropic_thin_pol3d.py
waveorder/models/isotropic_thin_3d.py
waveorder/models/phase_thick_3d.py

I'm documenting this change in its own PR for @edyoshikun, since it may affect his WIP. Tested with `recOrder`s `connect-reg-params` branch.

Remove kwargs from reconstructions

---

tests/models/test_phase_thick_3d.py
waveorder/models/inplane_anisotropic_thin_pol3d.py
waveorder/models/phase_thick_3d.py
waveorder/optics.py

This PR solves a common problem in "3D phase" reconstructions: you perform a reconstruction and see that the contrast is inverted. Should you flip the image? Flip the transfer function? Do these options add any computational expense?
This option lets you flip the transfer function without any additional computational expense or copying.  
Note: I have not added a similar option to `isotropic_thin_3d` because it takes a `z_position_list` directly, so the user can flip that list directly.

Add option for axial flip of `phase_thick_3d` transfer function

---

tests/models/test_isotropic_fluorescent_thick_3d.py
tests/models/test_isotropic_thin_3d.py
waveorder/models/inplane_oriented_thick_pol3d.py
waveorder/models/isotropic_fluorescent_thick_3d.py
waveorder/models/isotropic_thin_3d.py
waveorder/models/phase_thick_3d.py

This PR simplifies the parameter names for the `recOrder`-`waveorder` interface. 
This PR needs is matched with `recOrder` #381. Sorry for the headache @edyoshikun.

Match parameters to simplify `recOrder`-`waveorder` interface

---

examples/2D_QLIPP_simulation/2D_QLIPP_forward.py
examples/2D_QLIPP_simulation/2D_QLIPP_recon.py
examples/3D_PODT_phase_simulation/3D_PODT_Phase_forward.py
examples/3D_PODT_phase_simulation/3D_PODT_Phase_recon.py
examples/PTI_simulation/PTI_Simulation_Forward_2D3D.py
examples/PTI_simulation/PTI_Simulation_Recon2D.py
examples/PTI_simulation/PTI_Simulation_Recon3D.py
tests/reconstructor/test_2D_QLIPP_recon.py
tests/test_examples.py
waveorder/__init__.py
waveorder/optics.py
waveorder/waveorder_reconstructor.py

Fixes #133 and updates all of the CI-tested examples to use the individual modules instead of a global `wo` namespace. For example, the previous `wo.plot_multicolumn` becomes `visual.plot_multicolumn`. 
Also, removes unused imports from across `waveorder`.

Remove `__init__` imports

---

tests/test_focus_estimator.py
waveorder/focus.py

**Summary**
This PR fixes #129 and adds:
- an optional `plot_path` option...passing a path string will save a diagnostic plot to that path (`.png`, `.svg`, `.pdf` etc)
- an optional `threshold_FWHM` option (default 0) will make the function return an in-focus slice if the mid-band power peak has a FWHM larger than the threshold...otherwise the function will return `None`. 
**Rationale:**
After my initial conversation with @ieivanov, I looked for a way to "normalize" the mid-band power metric so that we could try using an absolute threshold. I ended up convincing myself that finding an absolute threshold would be challenging. 
For example, consider an in-focus object that fills the FOV then the same object that fills a small part of the FOV (padded with zeros/noise). If we normalize by the …

Add optional parameters `plot_path` and `threshold_FWHM` to `focus_from_transverse_band` 

---

waveorder/focus.py

**Before this PR:** if `threshold_FWHM = 0` (the default) and `peak_FWHM = 0` (a possibility with a noisy input), the focus finding algorithm will return `None`. This is a bug because it changes the previous behavior of the algorithm, and the documentation states that a slice will be returned if `threshold_FWHM = 0`. 
**After this PR:** if `threshold_FWHM = 0` and `peak_FWHM = 0`, the algorithm returns the peak's slice. 
Failing tests helped me catch this bug (:raised_hands:). @ieivanov the failure after several passing runs was due to random numbers in this test---thanks for flagging this.

Fix threshold-free focus-finding edge case 

---

waveorder/focus.py

`matplotlib.pyplot` figures remain open until explicitly closed. Calling `focus_from_transverse_band` multiple times keeps open figures in memory - we should close them after saving

close figure after saving

---

setup.cfg

Fixes #146. 
Removes dependencies that moved to `iohub`. 
See also: https://github.com/conda-forge/waveorder-feedstock/pull/9

Simplify dependencies

---

tests/models/test_inplane_oriented_thick_pol3D.py
tests/models/test_isotropic_fluorescent_thick_3d.py
tests/models/test_isotropic_thin_3d.py
tests/models/test_phase_thick_3d.py
tests/test_stokes.py
waveorder/models/inplane_oriented_thick_pol3d.py
waveorder/models/isotropic_fluorescent_thick_3d.py
waveorder/models/isotropic_thin_3d.py
waveorder/models/phase_thick_3d.py
waveorder/stokes.py

In [`recOrder` #248](https://github.com/mehta-lab/recOrder/pull/248) we added an orientation offset checkbox to `recOrder`'s GUI. 
This PR is a first step towards moving this logic to `waveorder` so that these options are more easily available. 
I've also added a `flip` option so that all combinations are covered. Following this merge, I will remove the business logic from `recOrder`, add another button to the `recOrder` GUI, then connect the `rotation` and `flip` buttons to the waveorder side.

Add rotate and flip orientation options to `waveorder` options

---

examples/models/inplane_oriented_thick_pol3D.py
waveorder/models/inplane_oriented_thick_pol3d.py
waveorder/models/isotropic_fluorescent_thick_3d.py
waveorder/models/isotropic_thin_3d.py
waveorder/models/phase_thick_3d.py

This PR makes `waveorder.model`s handle all rotational quantities in radians, and adds documentation to make that clear to users. 
The only "critical" change is to `inplane_oriented_thick_pol3d.apply_inverse_transfer_function`:
- **Before this PR:** returns retardance in units of `wavelength_illumination`
- **After this PR:** returns retardance in radians. 
I'm making this change here for two reasons:
- so that waveorder is consistent across reconstruction types. For example, the phase reconstructions all return phase values in radians, so it's reasonable to expect all other rotational quantities to be in radians. 
- so that I can handle [recOrder #390](https://github.com/mehta-lab/recOrder/issues/390) (retardance is in um not nm) in the simplest possible way. 
To be clear, I think …

`waveorder` handles all rotational quantities (including retardance) in radians

---

tests/models/test_inplane_oriented_thick_pol3D.py
tests/test_correction.py
waveorder/correction.py
waveorder/models/inplane_oriented_thick_pol3d.py

Introduced a new module `waveorder.correction` to replace the `waveorder.background_estimator`.
- Replaced the pseudo-OOP interface with functional API consistent with the rest of waveorder v2.
- Reduced lines of code for the same functionality from 300 to just 100.
- Enabled torch-based hardware acceleration.
- The new API is used for the `inplane_oriented_thick_pol3d` model. The waverorder reconstructor is still using the old one. Maybe they should both be moved into a `waveorder._deprecated` namespace?
The new method produces the same result:
```python
import matplotlib.pyplot as plt
import torch
from waveorder.background_estimator import BackgroundEstimator2D
from waveorder.correction import estimate_background
image = torch.zeros(360, 480)
image[:180, :] += 1
image[:, 120:360] += 1 …
```

Update background estimation to use torch

---

tests/conftest.py
tests/models/test_inplane_oriented_thick_pol3D.py
tests/test_correction.py
tests/test_stokes.py
waveorder/correction.py
waveorder/models/inplane_oriented_thick_pol3d.py
waveorder/stokes.py

Fixed the stokes module and its tests to work both on CPU and GPU.
Caveat: the background estimation in `waveorder.models.inplane_oriented_thick_pol3D.apply_inverse_transfer_function` ~is still NumPy code~ does not work with the MPS backend. See #153.
Tested on `cuda` (NVIDIA A40, CUDA 12.2; AMD EPYC 7302P, Linux 4.18.0) and `mps` (Apple M1 Pro, macOS 13.5.1), both with native PyTorch build from PyPI.
```text
tests/test_stokes.py::test_S2I_matrix PASSED                                                                    [  5%]
tests/test_stokes.py::test_I2S_matrix PASSED                                                                    [ 11%]
tests/test_stokes.py::test_s12_to_orientation[cpu] PASSED                                                       [ 17%] …
```

Device agnostic compute for polarization

---

examples/maintenance/PTI_simulation/README.md

In preparing for a `2.0.0` release, I tried running the reconstruction before the simulation and received a cryptic error. This PR documents the intended order

Document order-dependent scripts

---

README.md

M1 installation documentation

---

examples/documentation/PTI_experiment/PTI_Experiment_Recon3D_anisotropic_target_small.py
examples/documentation/PTI_experiment/README.md
examples/models/isotropic_thin_3d_resolution.py
waveorder/models/isotropic_thin_3d.py
waveorder/optics.py

This PR moves the PTI spoke-pattern data example from a jupyter notebook to a script and a static .html file. 
This PR also includes several suggestions from @mattersoflight to match the names to the most recent PTI submission:  
Some other TODOs/questions:

PTI example jupyter notebook to script and .html

---

tests/test_focus_estimator.py
waveorder/focus.py

Fixing bug related to focus finding in stack with only one slice. `in_focus_index=0` should be returned by `focus_from_transverse_band`, not `_check_focus_inputs`. `_check_focus_inputs` could also be refactored into two functions that 1. check the inputs and 2. determine the correct optimization function. This will remove possible confusion on `_check_focus_inputs` returning a callable.

fix bug finding focus in stack with only one slice

---

pyproject.toml

Right now PyTorch doesn't work with NumPy 2.0 on Windows:
https://github.com/pytorch/pytorch/issues/128860

Pin numpy <2

---

pyproject.toml

https://github.com/pytorch/pytorch/issues/128860 has been fixed in torch 2.4.1. The temporary pin in #173 is no longer necessary.
Edit: also bump the numpy requirement as recommended in [SPEC-0](https://scientific-python.org/specs/spec-0000/#2024---quarter-4).

Bump torch to unpin numpy

---

waveorder/models/isotropic_fluorescent_thick_3d.py
waveorder/models/isotropic_thin_3d.py
waveorder/models/phase_thick_3d.py
waveorder/sampling.py

Fixes #152. Fixes #172. 
This PR implements wrap-safe transfer functions. After this PR, undersampled data will not create wrapped transfer functions, which should address many of the reconstruction artifacts we've seen. 
Before (e.g. phase transfer function with transverse and axial wrapping):
After:
A prerequisite for this PR is a clear set of [transverse and axial Nyquist sampling rates](https://czbiohub.atlassian.net/wiki/spaces/TLG3Infect/pages/3671457799/2024-06-21+what+is+the+axial+Nyquist+sampling+rate). 
This PR redefines the `calculate_transfer_function` call so it should Just Work (™). The old calls have been renamed to `_calculate_wrap_unsafe_transfer_function`. Better naming suggestions are welcome. 
This PR implements these fixes for all of the transfer functions in the main …

Wrap-safe transfer functions

---

pyproject.toml
waveorder/models/isotropic_fluorescent_thick_3d.py
waveorder/models/isotropic_thin_3d.py
waveorder/scripts/visualize-greens.py
waveorder/scripts/visualize-support.py

This PR adds visualization scripts for the Green's tensor spectrum and transfer functions. 
Tagging @mattersoflight, @edyoshikun, @ieivanov who have requested these.  
Running these scripts results in:
https://github.com/user-attachments/assets/184b48c2-764b-4ea7-b649-05da67a96035
https://github.com/user-attachments/assets/8f3ac2d3-ece1-4913-95ad-31c9562abd13

Transfer function visuals

---

tests/test_filter.py
waveorder/filter.py
waveorder/models/inplane_oriented_thick_pol3d_vector.py
waveorder/models/isotropic_fluorescent_thick_3d.py
waveorder/models/isotropic_thin_3d.py
waveorder/models/phase_thick_3d.py
waveorder/reconstruct.py

This PR allows transfer functions to be calculated on smaller grids then applied to larger grids.  
This PR uses a `stretched_multiply` strategy for efficient application of a small OTF to a large dataset. This approach approximates the OTF as a piece-wise constant function, and applies this smaller array to datasets without upsampling. This approach allows us to reduce OTF memory requirements by as much as needed, trading OTF computational expense and OTF memory for accuracy.
To uniformly apply this strategy, I have implemented a new function `filter.apply_filter_bank`, which handles these the prepadding, stretched multiplications, matrix-vector bank multiplications, and unpadding. 
These three reconstructions now use a precomputed inverse filter bank and use the new shared …

Calculate transfer functions on grids smaller than data  

---

tests/cli_tests/test_settings.py
waveorder/cli/settings.py

`waveorder` checks that the ratios of several input parameters are not too different to guard against incorrect units. This PR changes these checks to raise warnings, not errors, because `waveorder` sometimes needs to reconstruct data collected with far-less-than-Nyquist sampling.

Settings-ratio checks should give warnings, not errors

---

waveorder/cli/utils.py

This PR skips the reconstruction of empty FOVs which results in NaNs in the zarr store and causes problems with downstream virtual staining

Skip reconstructions of empty FOVs

---

.github/workflows/test.yml
docs/examples/maintenance/PTI_simulation/PTI_Simulation_Forward_2D3D.py
tests/models/test_phase_thick_3d.py

This PR makes two tests smaller (phase invariance test and legacy PTI simulation) and fixes a test double trigger. These shorten the test suite from ~25 minutes (bottlenecked on macOS tests) to ~8 minutes (~bottlenecked on Windows pip installation).

Faster tests
